version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - gocritic
    - godot
    - gomoddirectives
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    godot:
      exclude:
        - ^ @.*
        - ^ (\d+)(\.|\)).*
    gosec:
      excludes:
        - G104
      config:
        global:
          audit: true
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
