before:
  hooks:
  - go mod tidy
  - go generate ./...
  - sh scripts/completions.sh
  - sh scripts/manpages.sh
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  ldflags:
  - -X 'github.com/tantalor93/dnspyre/v3/cmd.Version={{.Version}}-{{ .Os }}-{{ .Arch }}'
archives:
- id: dnspyre
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - LICENSE
  - README.md
  - completions/*
  - manpages/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
brews:
- repository:
    owner: tantalor93
    name: homebrew-dnspyre
  directory: Formula
  homepage: https://tantalor93.github.io/dnspyre/
  install: |-
    bin.install "dnspyre"
    bash_completion.install "completions/dnspyre.bash" => "_dnspyre"
    zsh_completion.install "completions/dnspyre.zsh" => "_dnspyre"
    man1.install "manpages/dnspyre.1.gz"
dockers:
- use: docker
  id: dnspyre
  dockerfile: "Dockerfile-goreleaser"
  image_templates:
  - "ghcr.io/tantalor93/dnspyre:{{ .Tag }}"
  - "ghcr.io/tantalor93/dnspyre:v{{ .Major }}"
  - "ghcr.io/tantalor93/dnspyre:v{{ .Major }}.{{ .Minor }}"
  - "ghcr.io/tantalor93/dnspyre:latest"
  build_flag_templates:
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.authors=Ondřej Benkovský <obenky@gmail.com>"
  - "--label=org.opencontainers.image.url=https://tantalor93.github.io/dnspyre"
  - "--label=org.opencontainers.image.documentation=https://tantalor93.github.io/dnspyre"
  - "--label=org.opencontainers.image.source=https://github.com/Tantalor93/dnspyre"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.licenses=MIT"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.description=tool for a high QPS DNS benchmark"
nfpms:
- package_name: dnspyre
  homepage: https://tantalor93.github.io/dnspyre
  maintainer: Ondřej Benkovský <obenky@gmail.com>
  description: |-
    tool for a high QPS DNS benchmark
  license: MIT
  formats:
  - apk
  - deb
  - rpm
